### ISSUE TITLE
YOLO字幕翻译错误

### ISSUE THREAD

**Issue by CheneyZeng** [udacity/cn-cv-issue-report#1]
## 课程导航+地址
例子：YOLO(https://classroom.udacity.com/nanodegrees/nd891/parts/827d2ba4-b67b-4146-bf74-a88a87f860a9/modules/80408aa5-e4a9-4e66-b599-a282402ee8f1/lessons/5a00ef90-53d9-4a9b-97cd-41ad778af664/concepts/2b5c2922-5c0e-437c-9c95-4ebaccdeea81#)

## 具体描述
视频ground truth vector 翻译成真实向量 确实很不好理解，但是也没错 
建议将ground truth 翻译成正确标注

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
