### ISSUE TITLE
计算机视觉入门，课程2， 概念10， 翻译错误

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#10]
## 课程导航+地址
概念 >  [彩色图像](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/a8d476e9-2cbc-4847-8bcc-eeb289140379)

## 具体描述
视频52s处字幕‘彩色图像对于某些分类任务并没有那么有效’，需改为‘彩色图像对于某些分类任务非常有用’

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
