### ISSUE TITLE
计算机视觉入门， 课程2， 概念12， 图片路径不对

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#11]
## 课程导航+地址
概念>  [Notebook: 可视化 RGB 通道](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/c1919384-90f8-43c1-9be2-9264c923ada3)

## 具体描述
notebook读取img的代码块， img的路径不对。 
image = mpimg.imread('images/wa_state_highway.jpg') 应改为：
image = mpimg.imread('wa_state_highway.jpg')

**Comment by xzenggit** [comment]
发现同样的错误，改正方法有效，谢谢。

**Comment by yifangwang08** [comment]
你好，谢谢你的反馈，该问题今天打开时发现路径已经更改。你可以再打开看看是否还存在问题。若是没有问题了，可以直接关掉该 issue 哦！

**Comment by CheneyZeng** [comment]
DONE
