### ISSUE TITLE
课程2：图像表示法和分类>  Notebook: 作为数字数据的图像 > 无法读取文件

### ISSUE THREAD

**Issue by xzenggit** [udacity/cn-cv-issue-report#12]
## 课程导航+地址
课程2：图像表示法和分类>  [Notebook: 作为数字数据的图像
](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/e992419d-7ea9-4d3a-87a1-5e1ee17bd093)

## 截图
<img width="637" alt="screen shot 2018-10-12 at 11 04 06 am" src="https://user-images.githubusercontent.com/8161792/46877316-8e79a180-ce0e-11e8-8f8e-d47ef4ac60c2.png">

## 具体描述
notebook 按照说明reset data后，仍然无法读取文件。

**Comment by JyiHUO** [comment]
路径改为：
```python
image = mpimg.imread('waymo_car.jpg')
```
主要是当前路径没有`images/`文件夹

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，学员反馈是 “读入并显示图像” 的代码块里 image = mpimg.imread('images/waymo_car.jpg')  该代码图片路径有误，该行代码应改为image = mpimg.imread('waymo_car.jpg')。

**Comment by CheneyZeng** [comment]
DONE
