### ISSUE TITLE
计算机视觉入门， 课程2， 概念20， 代码块应该是markdown

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#13]
## 课程导航+地址
课程2 > [Notebook: 加载和可视化数据](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/1e4985f8-6826-4639-97ec-6ce925380458#)

## 具体描述
代码块：
image_dir_training: the directory where our training image data is stored
image_dir_test: the directory where our test image data is stored

应该是markdown块。

**Comment by xzenggit** [comment]
发现同样的问题

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面问题是中文版的文件里将原本是 markdown 块的内容错弄成了代码块（英文版是正确的）。建议将中文版文件里的内容做修改，谢谢！

**Comment by CheneyZeng** [comment]
DONE
