### ISSUE TITLE
计算机视觉入门， 课程2， 概念20， 代码块报错

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#14]
## 课程导航+地址
课程2> [Notebook: 加载和可视化数据](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/1e4985f8-6826-4639-97ec-6ce925380458#)

## 具体描述
加载数据集的代码运行错误：

```python
# Using the load_dataset function in helpers.py
# Load training data
IMAGE_LIST = helpers.load_dataset(image_dir_training)

File "<ipython-input-4-49205fc513e9>", line 4
    ```python
    ^
SyntaxError: invalid syntax

**Comment by xzenggit** [comment]
去掉'```python'即可

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，学员反馈代码运行错误是因为代码块里多了 ```python ，有学员建议在 notebook 的文件里直接去掉该行。这个问题只在中文版里有，英文版是正确的。

**Comment by CheneyZeng** [comment]
DONE
