### ISSUE TITLE
YOLO 翻译错误 

### ISSUE THREAD

**Issue by jjjjohnson** [udacity/cn-cv-issue-report#16]
核心课程3 > 课程2 YOLO> [7. 生成边界框]https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/5a00ef90-53d9-4a9b-97cd-41ad778af664/concepts/be2bd17c-cb5e-4ec7-8266-e7fd9412f43c)

## 截图
![fine_grid](https://user-images.githubusercontent.com/20569095/46900374-a6672900-ced3-11e8-882f-64d59fbcd9ba.PNG)

## 具体描述
视频2分19秒处字幕 很好的网格，需改为 细小的网格

## 说明
根据上下文内容，fine grid 是指 网格把图片分成一块块很小的区域。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
