### ISSUE TITLE
计算机视觉入门， 课程3， 概念3， notebook没有翻译

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#19]
## 课程导航+地址
课程3 >  [3. Notebook：傅里叶变换](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/7d7fb885-e36c-4d48-bf16-635c64f7fd7b/concepts/734e007b-1950-45e9-92c4-27883cb6894e#)

## 具体描述
notebook是全英文的， 没有翻译。

**Comment by xzenggit** [comment]
发现了同样的问题

**Comment by CheneyZeng** [comment]
Done
