### ISSUE TITLE
P2的region proposal翻译错误

### ISSUE THREAD

**Issue by CheneyZeng** [udacity/cn-cv-issue-report#2]
## 课程导航+地址
例子：R-CNN ,FAST-RCNN,FATSTER-RCNN是基于区域的目标检测算法， 
其中 region proposals 应该翻译成候选区域而不是区域建议

## 具体描述
R-CNN ,FAST-RCNN,FATSTER-RCNN是基于区域的目标检测算法， 
其中 region proposals 应该翻译成候选区域而不是区域建议

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
