### ISSUE TITLE
计算机视觉入门， 课程3， 概念8， 数学公式的格式不对

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#20]
## 课程导航+地址
课程3 > [梯度和索贝尔过滤器](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/7d7fb885-e36c-4d48-bf16-635c64f7fd7b/concepts/6d172b51-9a35-434c-9226-bd3b276c6ff8)

## 具体描述
内容中：大小和方向两个部分里面的数学公式格式不对。 
大小
索贝尔还会检测哪些边缘最强，这一点体现在梯度大小上；大小越大，边缘越强。梯度的大小或绝对值是单个 x 和 y 梯度平方值的平方根。对于 xx 和 yy 方向的梯度，大小是平方和的平方根。

abs_sobelx = \sqrt{(sobel_x)^2}=(sobelx​)2​

abs_sobely = \sqrt{(sobel_y)^2}=(sobely​)2​

abs_sobelxy = \sqrt{(sobel_x)^2+(sobel_y)^2}=(sobelx​)2+(sobely​)2​

方向
在很多情形下，我们需要查找特定方向的边缘。例如，我们可能需要查找仅朝上或朝左的线条。通过单独计算 x 和 y 方向的图像梯度方向，我们可以判断该梯度的方向！

梯度方向是指 yy 梯度除以 xx 梯度的反正切:

tan^{-1}{(sobel_y/sobel_x)}tan−1(sobely​/sobelx​).

**Comment by yifangwang08** [comment]
你好，这是我看到的这部分内容的截图，麻烦你可以详细描述一下你觉得格式需要修改的地方吗？
![123](https://user-images.githubusercontent.com/43978415/47632677-13dab100-db86-11e8-8050-047a4a47d4eb.png)

**Comment by ibinlike** [comment]
现在看起来， 又正常了。 当时这个公式显示的有问题。 现在这样正确了。

**Comment by yifangwang08** [comment]
> 现在看起来， 又正常了。 当时这个公式显示的有问题。 现在这样正确了。

嗯，好哒。谢谢你的反馈！
