### ISSUE TITLE
计算机视觉入门， 课程3， 概念13， notebook没有翻译

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#21]
## 课程导航+地址
课程3 > [13. Notebook：过滤器的傅里叶变换](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/7d7fb885-e36c-4d48-bf16-635c64f7fd7b/concepts/ac034bcb-0c6b-44a8-9abe-432d23a1a9b3#)

## 具体描述
notebook没有翻译

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
