### ISSUE TITLE
计算机视觉入门 ，课程3， 概念24， notebook没有翻译

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#22]
## 课程导航+地址
课程3 > [24. Notebook：哈尔特征脸部检测](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/7d7fb885-e36c-4d48-bf16-635c64f7fd7b/concepts/ae4cc112-0009-4303-9fcd-e2352d95cffe#)

## 具体描述
notebook 没有翻译

**Comment by CheneyZeng** [comment]
DONE
