### ISSUE TITLE
计算机视觉入门->图像表示法和分类->划分数据（描述不准确）

### ISSUE THREAD

**Issue by JyiHUO** [udacity/cn-cv-issue-report#25]
## 课程导航+地址
课程1->图像表示法和分类->[划分数据](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/0f8cec10-5e08-4428-b395-160a458b6a1d#)

## 具体描述
表述不准确

原描述：即选择划分任何给定数据的最佳算法

改为：即选择最佳划分线来划分任何给定数据的算法

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
