### ISSUE TITLE
高级计算机计算与深度学习> 7. 图像说明> 概念 1 - 7 都没有 中文字幕

### ISSUE THREAD

**Issue by jjjjohnson** [udacity/cn-cv-issue-report#27]
## 课程导航+地址
高级计算机计算与深度学习 > 图像说明 > [1. 图像说明简介](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/63ab2258-c681-410d-8aae-5cba7030b2af/concepts/2080da18-31a7-4280-a89d-b492da176a40)

高级计算机计算与深度学习 > 图像说明 > [2. 利用神经网络]

一直到 7.标记话说明 都没有中文字幕

## 截图
![default](https://user-images.githubusercontent.com/20569095/46912433-b94b2d80-cfa7-11e8-9efb-ff5bf767459f.PNG)

**Comment by yifangwang08** [comment]
你好，我们已对视频的字幕进行了更新，谢谢你的反馈！
