### ISSUE TITLE
计算机视觉入门， 课程1 概念1， 翻译不准确

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#3]
概念> 简介 > [欢迎学习计算机视觉纳米学位课程](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/2b49053d-f01d-4a95-b02c-47f96c544e42/concepts/f4dcb3f1-95ce-4ecf-b04c-01bde1257b7b)

## 具体描述
视频34s处字幕“甚至包括我与所有这些物体的关系”，需改为’甚至包括我与所有这些物体的位置关系‘

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
