### ISSUE TITLE
计算机视觉入门，课程4， 概念7和8重复了

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#31]
## 课程导航+地址

计算机视觉 > 简介 > [7. Notebook：查找轮廓和特征](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/4f54a275-2dae-4a57-b769-8b83aee913c8/concepts/7940b6de-4808-4e7a-8a42-9b1b0097a853)

## 具体描述
此处跟[8. 解决方案：查找轮廓和特征] 重复吗？还是8就是7的答案？
[https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/4f54a275-2dae-4a57-b769-8b83aee913c8/concepts/97e5da11-9497-4bbe-aa84-c9460b6863f4]

**Comment by JyiHUO** [comment]
notebook7中有部分代码是事例代码，不应该被用来作为可运行的代码，比如说在notebook7的以下这行代码：

![image](https://user-images.githubusercontent.com/16526817/47630476-facd0280-db7b-11e8-9df7-87ff81796fcc.png)

在notebook8是作为事例代码出现的：

![image](https://user-images.githubusercontent.com/16526817/47630513-29e37400-db7c-11e8-8691-0eb997f0d814.png)

所以notebook7的这些代码要被修改

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面提到 notebook 7 里的代码需要修改，麻烦你看一下~

**Comment by CheneyZeng** [comment]
感谢！是的！DONE
