### ISSUE TITLE
计算机视觉入门， 课程5， 概念14， 代码报错

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#32]
## 课程导航+地址
计算机视觉入门 > 特征向量 > [14. 实施HOG](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/913d992a-a36a-4741-b448-b2221d6fabf0/concepts/1b9b5e05-191a-49aa-bd27-49447f3d9ccd)

## 具体描述
第一个代码块无法运行：

<br><br>
Histograms of Oriented Gradients (HOG)
<br><br><br>

  File "<ipython-input-1-52180df1decf>", line 1
    <br><br>
    ^
SyntaxError: invalid syntax

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面提到的代码运行报错，麻烦看一下是操作的问题还是代码错误。要是代码没错的话可以跟学员解释一下~

**Comment by CheneyZeng** [comment]
DONE
