### ISSUE TITLE
计算机视觉入门， 课程5， 概念14，代码块错误

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#33]
## 课程导航+地址
计算机视觉入门 > 特征向量 > [14. notebook：实施HOG] > [2.example-zh]>(https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/913d992a-a36a-4741-b448-b2221d6fabf0/concepts/1b9b5e05-191a-49aa-bd27-49447f3d9ccd#
)

## 截图
![hog](https://user-images.githubusercontent.com/12690686/46917355-d1976880-cff8-11e8-99c0-6380edae3cd4.PNG)

## 具体描述
不知道该代码块的作用是什么。

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面提到的代码错误麻烦你确认一下。要是没错的话可以跟学员解释一下~

**Comment by CheneyZeng** [comment]
这是Markdown
DONE
