### ISSUE TITLE
计算机视觉入门， 课程1， 概念3 文字重复

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#4]
## 课程导航+地址
概念 >  [项目和主题](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/2b49053d-f01d-4a95-b02c-47f96c544e42/concepts/e9df2466-e07c-4731-98c1-bbd7543fd3b9)

## 具体描述
计算机视觉简介 - 介绍了**了**以下内容：图像处理、手动提取特征或使用 PyTorch 训练卷积神经网络提取特征。 --多了一个’了‘。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
