### ISSUE TITLE
对象跟踪与定位》动作简介》Notebook：光流法和动作向量

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#41]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/cf6698d7-ec93-4a77-a34d-731f2616ebcb/concepts/31fb2edd-63f5-49fe-88f0-4600bd387170

## 具体描述
打开界面是英文的
应该改成中文界面（有中文界面，点击左上角 notebook 图标）

**Comment by yifangwang08** [comment]
感谢你的反馈！针对默认链接是英文的问题我们正在解决。
