### ISSUE TITLE
对象跟踪与定位 》 机器人定位 》 8.感知之后的概率

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#42]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/08551158-d67c-4ea7-8a95-ccfaa3871b97/concepts/e22f533c-6b9e-4f6f-98a7-7e094ea5e0d3

## 具体描述
两个习题描述中，格式错误
* x2 应该为 $x_2$ （x下标2）
* x1 应该为 $x_1$ （x下标1）

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
