### ISSUE TITLE
 对象跟踪与定位 》 机器人定位 》12. Notebook：传感函数

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#43]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/08551158-d67c-4ea7-8a95-ccfaa3871b97/concepts/a9b97652-1dc0-45dc-9bed-10a6591d9237#

## 具体描述
内容错误！
* “机器人对颜色感知错误的概率是`pHit = 0.6`”
应改为 “机器人对颜色感知错误的概率是pMiss = 0.2。 ”

**Comment by CheneyZeng** [comment]
DONE
