### ISSUE TITLE
 对象跟踪与定位 》 机器人定位 》32. Notebook：移动多次

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#44]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/08551158-d67c-4ea7-8a95-ccfaa3871b97/concepts/6718910a-e5e6-47cc-b3f6-b269e926d384

## 具体描述
中文notebook有两个错误
* 图片显示错误
* 练习内容错误，是移动1000次，不是移动两次。

**Comment by yifangwang08** [comment]
@CheneyZeng @ChengGoooo 这里面提到的问题是中文版 notebook 里图片显示不出来及练习内容翻译过来错误（英文版 notebook 里的图片可以正常显示）

**Comment by CheneyZeng** [comment]
@ChengGoooo  这个workspace的文件错了，应该是multiple movements；

**Comment by sylviasun916** [comment]
已修改完成，感谢反馈！
