### ISSUE TITLE
 对象跟踪与定位 》 机器人定位 》34. Notebook：感知和移动循环

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#45]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/08551158-d67c-4ea7-8a95-ccfaa3871b97/concepts/299c4f56-dcb6-46d6-9f11-3774e7397473

## 具体描述
中文notebook中练习题描述时出现格式错误
* 原先是
```
### 练习：给定列表为motions=[1,1]，如果机器人首先感知到红色，则计算后验分布，然后向右移动一个单位，然后感知绿色，之后再次向右移动，从均匀的先验分布`p`开始。
```
应改为
```
### 练习：
给定列表为motions=[1,1]，如果机器人首先感知到红色，则计算后验分布，然后向右移动一个单位，然后感知绿色，之后再次向右移动，从均匀的先验分布`p`开始。
```

**Comment by CheneyZeng** [comment]
DONE
