### ISSUE TITLE
计算机视觉入门>课程14>概念12， notebook链接到英文版的notebook了

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#46]
## 课程导航+地址
计算机视觉入门>课程14> > [Notebook：可视化 FashionMNIST](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/68357628-74e3-439a-beb6-12884a1fb5d8/concepts/7304b1ce-fe43-4928-8b4a-c723fc473b7e#)

![image](https://user-images.githubusercontent.com/12690686/47000198-51891400-d15a-11e8-863b-aae2b1772ebd.png)

## 具体描述
notebook目录下有中文版， 但是课程链接是指向英文版的notebook。

**Comment by CheneyZeng** [comment]
Done
