### ISSUE TITLE
计算机视觉入门>课程14>概念14， notebook链接为英文版

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#47]
## 课程导航+地址
计算机视觉入门>课程14 > [14. Notebook：Fashion MNIST 训练练习](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/68357628-74e3-439a-beb6-12884a1fb5d8/concepts/ee50b565-ef2d-435a-b9ff-d8bdb3c87ae8#)

## 截图
![image](https://user-images.githubusercontent.com/12690686/47000345-a4fb6200-d15a-11e8-84a0-7be429c6ada4.png)

![image](https://user-images.githubusercontent.com/12690686/47000387-be9ca980-d15a-11e8-868c-5a00ea16b0df.png)

## 具体描述
课程链接到英文版的notebook了， 应该链接到中文版的。

**Comment by CheneyZeng** [comment]
DONE
