### ISSUE TITLE
计算机视觉入门>课程14>概念15： notebook链接到了英文版本

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#48]
## 课程导航+地址
计算机视觉入门>课程14 > [15. Notebook：FashionMNIST，解决方案 1](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/68357628-74e3-439a-beb6-12884a1fb5d8/concepts/a70c428c-b6fb-4bb3-9b29-05d1bc420336#)

## 截图

![image](https://user-images.githubusercontent.com/12690686/47001094-43d48e00-d15c-11e8-8955-8169ff10568e.png)

## 具体描述
课程链接到英文版notebook了， 需要改链接。

**Comment by CheneyZeng** [comment]
DONE
