### ISSUE TITLE
计算机视觉入门>课程14>概念24， notebook链接到英文版了。 

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#49]
## 课程导航+地址
计算机视觉入门>课程14> [24. Notebook：FashionMNIST 特征可视化](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/68357628-74e3-439a-beb6-12884a1fb5d8/concepts/c6046adf-4584-416a-b2aa-d56755da8351#)

## 截图
![image](https://user-images.githubusercontent.com/12690686/47004720-c2352e00-d164-11e8-8230-aabd69fb9e89.png)

## 具体描述
课程链接到英文版notebook去了。

**Comment by CheneyZeng** [comment]
DONE
