### ISSUE TITLE
计算机视觉入门， 课程1， 概念4， 翻译不合适

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#5]
## 课程导航+地址
概念 > [与行业领先者合作](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/2b49053d-f01d-4a95-b02c-47f96c544e42/concepts/3ef13377-86bd-4b1e-a6d3-e289f87c9cbf)

## 具体描述
视频3：33s处字幕“驱动器 PX2”，需改为“Driver PX2”

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
