### ISSUE TITLE
计算机视觉入门>课程14>概念25， notebook链接到英文版了。 

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#50]
## 课程导航+地址
计算机视觉入门>课程14 > [25. Notebook：可视化网络层级](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/68357628-74e3-439a-beb6-12884a1fb5d8/concepts/20c9562e-caf9-4403-9d8a-b5acbb760155#)

## 截图

![image](https://user-images.githubusercontent.com/12690686/47005027-76cf4f80-d165-11e8-82be-ede1719d014a.png)

## 具体描述
课程链接到英文版notebook了。

**Comment by CheneyZeng** [comment]
DONE
