### ISSUE TITLE
计算机视觉入门 > 课程2 > 概念3， 翻译问题

### ISSUE THREAD

**Issue by zchan0** [udacity/cn-cv-issue-report#51]
## 课程导航+地址
课程 2: 图像表示法和分类 > [3. 计算机视觉管道](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/419af5fa-27bd-49ea-9c07-1abaa0670856#)

## 截图 1
<img width="578" alt="image-20181016214219620" src="https://user-images.githubusercontent.com/5645229/47021131-6cc14700-d18d-11e8-9a09-07a6d22bce45.png">

## 具体描述 1
00:24 - Each frame is then sent through some preprocessing steps that enhance the quality and detail of the image.

然后通过预处理步骤发送每一帧提高图像的质量和细节	// “发送”翻译出来比较生硬，而且因果关系没有表达出来。

建议：然后每一帧通过一些预处理步骤来提高图片的质量和增强图片的细节

## 截图 2
<img width="579" alt="screenshot 2018-10-16 21 42 45" src="https://user-images.githubusercontent.com/5645229/47021282-b4e06980-d18d-11e8-9bbb-d00d0733fa4f.png">

## 具体描述 2
00:33 - You may also perform other transformations here such as changing from color to grayscale. 

transformations 翻译成“变换”比“转换”要常用一些，“把颜色改为灰度” 这句其实应该补充更多细节，初学者可能并不知道什么是灰度图。

建议：你也可以做一些其它变换，比如将有色图变成灰度图。

## 截图 3
<img width="573" alt="screenshot 2018-10-16 21 43 26" src="https://user-images.githubusercontent.com/5645229/47021353-d6415580-d18d-11e8-8d80-b3d6be692956.png">

## 具体描述 3
00:36 - Next, to these images are analyzed and ...

接下来分析这些图像  // 这里应该是被动关系

建议：接下来，对于这些已经处理过的图像

## 截图 4
<img width="574" alt="screenshot 2018-10-16 21 44 17" src="https://user-images.githubusercontent.com/5645229/47021411-fd982280-d18d-11e8-8969-bd7590f5599e.png">

## 具体描述 4
1:00 - an application can then act on this and interact ...

应用程序可以做出行动	// act on this 翻译省略了这里的逻辑关系

建议：应用程序可以基于识别的情感做出行动

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
