### ISSUE TITLE
对象跟踪与定位，课程5概念3,  字幕问题

### ISSUE THREAD

**Issue by YCSU** [udacity/cn-cv-issue-report#53]
## 课程导航+地址
对象跟踪与定位 > 状态与移动 >[3.移动模型](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/1b064436-e597-48bb-81c0-f4ef5391f444/concepts/2eed8e52-148e-4fce-a7c6-4bc882b130ce)

## 具体描述
视频1:34s处字幕出现时间标记

**Comment by yifangwang08** [comment]
@YCSU  你好，麻烦你可以加下截图或者详细说明一下问题吗？不是很明白你提到的“时间标记”是什么意思，我在视频里并没有发现问题。谢谢！

**Comment by YCSU** [comment]
截图时间标记
![issue 53](https://user-images.githubusercontent.com/7635036/47564400-78fc8f80-d957-11e8-814c-ea4a3154911a.PNG)

**Comment by yifangwang08** [comment]
> 截图时间标记
> ![issue 53](https://user-images.githubusercontent.com/7635036/47564400-78fc8f80-d957-11e8-814c-ea4a3154911a.PNG)

嗯，好的！谢谢！

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
