### ISSUE TITLE
对象跟踪与定位，课程5概念5, 错字

### ISSUE THREAD

**Issue by YCSU** [udacity/cn-cv-issue-report#54]
## 课程导航+地址
对象跟踪与定位 > 状态与移动>[5.一个不同的模型 ](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/1b064436-e597-48bb-81c0-f4ef5391f444/concepts/27b1cdcd-bda5-494b-abf6-b8d9cbb6c7b1)

#### 加速度
__如果车辆的加速度为-20 m/s^__
应为
__如果车辆的加速度为-20 m/s^2__

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
