### ISSUE TITLE
对象跟踪与定位，课程6概念11, 错字

### ISSUE THREAD

**Issue by YCSU** [udacity/cn-cv-issue-report#55]
## 课程导航+地址
对象跟踪与定位 > 矩阵与状态变换 > [11.使用矩阵表示状态](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/5922a820-02ac-4075-b38d-77505b5e32bc/concepts/4b987431-6149-4fc3-a197-925128a457c3)

## 具体描述
__The 状态向量__
应为
__状态向量__

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改!
