### ISSUE TITLE
计算机视觉入门， 课程3， 概念12， notebook没有翻译

### ISSUE THREAD

**Issue by JyiHUO** [udacity/cn-cv-issue-report#56]
## 课程导航+地址
计算机视觉入门， 课程3， 概念12， [notebook没有翻译](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/7d7fb885-e36c-4d48-bf16-635c64f7fd7b/concepts/73481472-3436-4b1b-b298-5ed4debd4550#)

## 具体描述
notebook没有翻译

**Comment by CheneyZeng** [comment]
DONE
