### ISSUE TITLE
对象跟踪与定位，课程7概念4, 影片内容似乎有误

### ISSUE THREAD

**Issue by YCSU** [udacity/cn-cv-issue-report#58]
## 课程导航+地址
对象跟踪与定位 > 即时定位与地图构建 > [4.练习：实施约束条件](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/717c9878-7193-4d3c-a792-2c0858fcbec8/concepts/734c13b4-4aeb-446b-8fda-8229254f9f5a)

对象跟踪与定位 > 即时定位与地图构建 > [5.答案：实施约束条件](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/717c9878-7193-4d3c-a792-2c0858fcbec8/concepts/20890061-cf36-40ed-80b2-a5a401217a88)

与后续影片

## 具体描述
视频1:46s处  影片右下標示
 x_1 -> x_2 - 4

但根据语音与下面练习题的答案，应标示为
x_2 -> x_1 - 4

概念5与后续影片整段皆是

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面提到的问题需要你确认一下是否有误~

**Comment by CheneyZeng** [comment]
我做了一遍，是应该改成 x_2 -> x_1 - 4；我赞同；
