### ISSUE TITLE
欢迎学习计算机视觉课程 > 概念 > 4.与行业领军者合作 >字幕翻译问题

### ISSUE THREAD

**Issue by xzenggit** [udacity/cn-cv-issue-report#6]
## 课程导航+地址
课程1：欢迎学习计算机视觉课程 > 概念 > [4.与行业领军者合作](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/2b49053d-f01d-4a95-b02c-47f96c544e42/concepts/3ef13377-86bd-4b1e-a6d3-e289f87c9cbf#)

## 截图
<img width="810" alt="screen shot 2018-10-12 at 9 45 23 am" src="https://user-images.githubusercontent.com/8161792/46873974-055e6c80-ce06-11e8-9073-349cd80cb256.png">

<img width="805" alt="screen shot 2018-10-12 at 10 04 29 am" src="https://user-images.githubusercontent.com/8161792/46874076-4a829e80-ce06-11e8-90e5-a94cdfe6c1a4.png">

<img width="799" alt="screen shot 2018-10-12 at 10 11 46 am" src="https://user-images.githubusercontent.com/8161792/46874499-44d98880-ce07-11e8-8e2c-e54c38a78d9c.png">

## 具体描述
视频2:51处字幕“PC”，最好改为“个人电脑”。
视频2:54处字幕“两个车道”，最好改为“两个通道”或者“双通道”。
视频4:14处字幕最好改为“一个完整的针对特定交通设备的无人驾驶系统”。

此外，字幕背景和字幕字体本身颜色太相近，导致看字幕非常容易眼疲劳。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
