### ISSUE TITLE
对象跟踪与定位，课程7概念19 and 20标题翻译

### ISSUE THREAD

**Issue by YCSU** [udacity/cn-cv-issue-report#60]
## 课程导航+地址
对象跟踪与定位 > 即时定位与地图构建 >[19. 自信的测量值](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/717c9878-7193-4d3c-a792-2c0858fcbec8/concepts/1566d2a7-21d5-4275-8073-576480b5c683)
对象跟踪与定位 > 即时定位与地图构建 >[20. Notebook:自信的测量值](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/717c9878-7193-4d3c-a792-2c0858fcbec8/concepts/0c5e59de-5a57-4ab4-8930-1f8e7374e0e0)

## 具体描述
标题翻译为**自信的测量值**，可能改译为**测量值的置信水平**较为恰当

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面提到的标题的翻译麻烦你看下按学员的建议更改是否更合适，谢谢！

**Comment by yifangwang08** [comment]
感谢反馈！
