### ISSUE TITLE
高级计算机视觉，项目图像标注

### ISSUE THREAD

**Issue by L1aoXingyu** [udacity/cn-cv-issue-report#62]
## 图像标注项目
workspace 里面需要自己下载数据集，但是下载到一半会中断

**Comment by L1aoXingyu** [comment]
我查看了前面的说明，发现要打开gpu好像可以load数据，但是具体没有去试，我觉得应该在不开gpu的时候也提供数据，毕竟前面的代码需要数据去测试模型是不是写对

**Comment by yifangwang08** [comment]
@ChengGoooo @CheneyZeng  麻烦评估一下同学提的建议的可行性，谢谢！

**Comment by CheneyZeng** [comment]
好哒，我们给CD提了issue啦，目前看起来GPU格式下是没问题的～
