### ISSUE TITLE
对象跟踪定位 》 卡曼滤波器简介 》 14。参数更新 ： 无中文字幕

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#63]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/882eb101-8593-4301-a41a-c9be6b3f40c6/concepts/77c32ab6-c398-4d3d-8743-f7d6eee8fddb

无中文字幕

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这个 issue 里提到没有字幕，麻烦你看一下

**Comment by sylviasun916** [comment]
已修改 添加中英文字幕，感谢反馈！ （脚本需要一点时间 在教室中显示）
