### ISSUE TITLE
对象跟踪定位 》 卡曼滤波器简介 》 24：中文notebook 未完成

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#64]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/882eb101-8593-4301-a41a-c9be6b3f40c6/concepts/05638a56-1fdb-4702-a215-a6c59aa05186#

## 具体描述

中文notebook 是个 md 文件

**Comment by CheneyZeng** [comment]
@sylviasun916  求助～

**Comment by sylviasun916** [comment]
已修改 感谢反馈！ 

@CheneyZeng Hi Rita, 可以后续直接参考之前分享的攻略，将 md 文件转成 ipynb 文件哦。
