### ISSUE TITLE
计算机视觉入门，课程2， 概念31，notebook问题

### ISSUE THREAD

**Issue by xzenggit** [udacity/cn-cv-issue-report#66]
## 课程导航+地址
计算机视觉入门 > 课程2 > [31.Notebook: 准确性和错误分类](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/ed7bc36f-f7c3-4c28-a2fe-e4f8e9eb85fb#)

## 截图
<img width="759" alt="screen shot 2018-10-20 at 11 01 50 am" src="https://user-images.githubusercontent.com/8161792/47257489-86e47900-d45c-11e8-950c-495805b45fc3.png">
<img width="729" alt="screen shot 2018-10-20 at 11 36 48 am" src="https://user-images.githubusercontent.com/8161792/47257490-86e47900-d45c-11e8-8390-e6a86cdec0de.png">

## 具体描述
以上截图，一处应该为 markdown，另一处应该去掉 ````python`

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，麻烦你帮忙看下这个 issue 是否需要修改，我看有代码在里面怕改错~

**Comment by CheneyZeng** [comment]
DONE
