### ISSUE TITLE
超参数 -> RNN 超参数 翻译错误

### ISSUE THREAD

**Issue by jjjjohnson** [udacity/cn-cv-issue-report#67]
高级计算机视觉与深度学习 > 超参数 > [1.  RNN超参数](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/5c4faf40-5fa7-4004-85cf-ff7e86d596a0/concepts/a8510236-a0fe-41f3-9d19-254394349820)

## 截图
![default](https://user-images.githubusercontent.com/20569095/47339805-e9dd4680-d6ce-11e8-94d5-7cbe5ce1c501.png)

## 具体描述
视频1分58s处字幕 显示在**没有 LSTM cell的情况下**，需改为：显示在**有 LSTM cell的情况下**

## 说明
我看了视频中提到的文章 Neural Speech Recognizer: Acoustic-to-Word LSTM Model for Large Vocabulary Speech Recognition
文章提到用 deep bi-directional LSTM RNNs with CTC loss 做的实验。

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这里面学员提出疑问，可能是我们的讲师讲错了。考虑到学科专业性，麻烦你看一下是不是讲师讲错了？ 如果是，我们可以在讲师注释里补充说明一下，如果无问题，也可以和学员解释一下, close ticket 哦，感谢！

**Comment by CheneyZeng** [comment]
嗯嗯，这个项目在GPU下可以的哦～感谢你～
