### ISSUE TITLE
深度学习注意力机制 > 注意力简介 没有中文字幕

### ISSUE THREAD

**Issue by jjjjohnson** [udacity/cn-cv-issue-report#68]
高级计算机视觉与深度学习 > 深度学习注意力机制 > [1. 注意力简介](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/19fb83fb-c9c4-4b54-bba6-30e9f184a925/concepts/22752599-fa1f-4eed-a7ef-844611060e21)

## 截图
![jt2](https://user-images.githubusercontent.com/20569095/47339957-607a4400-d6cf-11e8-979e-4e6789486918.png)

**Comment by yifangwang08** [comment]
@sylviasun916  圆圆，这里面提到的缺少中文字幕麻烦你帮忙看下

**Comment by sylviasun916** [comment]
HI @yifangwang08  这是有中文字幕的哦。 可能是由于翻墙问题没正确显示。 我已添加在 AWS 上。
