### ISSUE TITLE
对象跟踪与定位 》 即时定位与地图构建 》 3 答案 图形SLAM  》 错误

### ISSUE THREAD

**Issue by TrW236** [udacity/cn-cv-issue-report#69]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/717c9878-7193-4d3c-a792-2c0858fcbec8/concepts/1f34591d-8fb4-4c27-b9b4-187a367f56de

## 具体描述
`例如在我们的示例中：姿势 x3`
应改为 `例如在我们的示例中：姿势 x2`

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，这个麻烦你看下是否有错，要是没错的话可以跟学员解释一下~

**Comment by CheneyZeng** [comment]
感谢！是的，机器人只能向前和向下， 只有两个姿势没有意义。DONE
