### ISSUE TITLE
欢迎学习计算机视觉课程 > 概念 > 6.优达学城的学习支持 > 格式问题

### ISSUE THREAD

**Issue by xzenggit** [udacity/cn-cv-issue-report#7]
## 课程导航+地址
课程1：欢迎学习计算机视觉课程 > 概念 > [6.优达学城的学习支持](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/2b49053d-f01d-4a95-b02c-47f96c544e42/concepts/019784af-822b-483b-b0a6-ce22ce07ffa2)

## 截图
<img width="694" alt="screen shot 2018-10-12 at 10 18 05 am" src="https://user-images.githubusercontent.com/8161792/46874844-258f2b00-ce08-11e8-988a-a17656b41dee.png">

## 具体描述
最后面邮箱地址显示貌似有markdown的格式显示问题。

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
