### ISSUE TITLE
高级计算机视觉与深度学习--项目：图像标注，

### ISSUE THREAD

**Issue by davincizhao** [udacity/cn-cv-issue-report#71]
## 截图
![s1](https://user-images.githubusercontent.com/22903476/47397341-8d376580-d77a-11e8-9a2d-71cc9f21393b.png)

## 具体描述
1_Preliminaries.ipynb 文件名，改成1_Preliminaries-zh.ipynb

**Comment by CheneyZeng** [comment]
DONE
