### ISSUE TITLE
计算机视觉入门， 课程2 练习notebook的图片路径不对

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#8]
## 课程导航+地址
课程2 > [Notebook: 作为数字数据的图像](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/e992419d-7ea9-4d3a-87a1-5e1ee17bd093#)

## 具体描述
notebook第二个代码块， 读取图片的代码， 代码路径不对。 
应该把：image = mpimg.imread('images/waymo_car.jpg') 
改成：image = mpimg.imread('waymo_car.jpg')

**Comment by yifangwang08** [comment]
感谢反馈！我们正在对该问题进行修改
