### ISSUE TITLE
对象跟踪与定位 课程2 概念4

### ISSUE THREAD

**Issue by zhouker94** [udacity/cn-cv-issue-report#81]
## 课程导航+地址
https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/08551158-d67c-4ea7-8a95-ccfaa3871b97/concepts/8eae28fd-2776-4a44-89b3-0b64c82aabfb

## 截图
<img width="691" alt="image" src="https://user-images.githubusercontent.com/24894165/47641503-5ddd8a00-dbba-11e8-8202-02105fa75e5f.png">

## 具体描述
此处"Uncertainty" 应该翻译为 **不确定度** 更为贴切

**Comment by ghost** [comment]
可是原文现在写的是“an uncertain quantity”😂

**Comment by zhouker94** [comment]
> 可是原文现在写的是“an uncertain quantity”😂

就是猛然看到这个翻译觉得有点费解哈哈哈，我也没想到很好的翻译

**Comment by ghost** [comment]
我们也没想到。。。。但是感觉直译又有点别扭。

先这样放着吧😂

**Comment by ghost** [comment]
有什么好想法可以再来开启
