### ISSUE TITLE
对象跟踪与定位 > 动作简介 > 6 亮度恒定假定

### ISSUE THREAD

**Issue by yifangwang08** [udacity/cn-cv-issue-report#87]
## 课程导航+地址
对象跟踪与定位 > 动作简介 > [6. 亮度恒定假定](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/cf6698d7-ec93-4a77-a34d-731f2616ebcb/concepts/8979533d-9db8-45a5-b50f-1e4ce22fa8db)

## 问题描述
标题感觉不是很合适，视频和文字中共说了两个假定，一个是亮度恒定，一个是邻近像素具有相同的动作，建议标题要么改成两个假定 或者将两个具体的假定都说明，只说一个有误导

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，学员反映该节的标题不合适，麻烦你看下是否需要更改，不需要的话可以直接关掉 issue~

**Comment by CheneyZeng** [comment]
感谢！DONE
