### ISSUE TITLE
对象跟踪与定位 > 动作简介 > Notebook：光流法和动作向量

### ISSUE THREAD

**Issue by yifangwang08** [udacity/cn-cv-issue-report#88]
## 课程导航+地址
对象跟踪与定位 > 动作简介 > [Notebook：光流法和动作向量](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/a954f184-f612-4d17-83b5-1169686cb3ed/modules/f7e98583-8c85-4a37-b6b5-b39fed4fc2f3/lessons/cf6698d7-ec93-4a77-a34d-731f2616ebcb/concepts/31fb2edd-63f5-49fe-88f0-4600bd387170#)

## 截图
![111](https://user-images.githubusercontent.com/43978415/47708498-2d085e00-dc69-11e8-946f-cae9d5ae0ba2.JPG)

## 具体描述
链接处的文字"documented,here "  中间的逗号有点怪异 （英文版 notebook）

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，学员反映该 notebook 英文版中"documented,here " 中间的逗号有点怪异，麻烦你评估下是否需要做修改，谢谢！

**Comment by CheneyZeng** [comment]
DONE
