### ISSUE TITLE
对象跟踪与定位 > 机器人定位 > 5.定位/7.Notebook:一维机器人世界

### ISSUE THREAD

**Issue by yifangwang08** [udacity/cn-cv-issue-report#89]
## 具体描述
文中给出的 github 练习代码库里的Notebook文件都是英文原版的，不是本地化之后的

**Comment by yifangwang08** [comment]
@CheneyZeng  Rita，学员反馈给的 github 链接里的 notebook 未做本地化，麻烦你看下是否需要加入对应的中文版 notebook。Github 链接为 https://github.com/udacity/CVND_Localization_Exercises

**Comment by CheneyZeng** [comment]
DONE
