### ISSUE TITLE
计算机视觉入门， 课程2，概念10, 翻译问题

### ISSUE THREAD

**Issue by ibinlike** [udacity/cn-cv-issue-report#9]
## 课程导航+地址
概念 > [彩色图像](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/f0cea37f-3e44-4efa-ae6b-480b3782e219/modules/e3a3ea05-b2e8-4159-82c7-55332119239b/lessons/c75c735c-c163-41b8-99b4-f0af0e607234/concepts/a8d476e9-2cbc-4847-8bcc-eeb289140379)

## 截图
<img width="1212" alt="demo" src="https://github.com/udacity/intro2car-cn_feedback/blob/master/beta-test/Sebastrian.png">

## 具体描述
视频51s处字幕’它们更加复杂‘，需改为‘它们会增加不必要的复杂性’

**Comment by yifangwang08** [comment]
感谢反馈！我们已对该问题进行了修改
