### ISSUE TITLE
高级计算机计算与深度学习> RNN > [6.前馈过程] 变量的 Latex 渲染

### ISSUE THREAD

**Issue by ghost** [udacity/cn-cv-issue-report#90]
## 课程导航+地址
高级计算机计算与深度学习> RNN > [6.前馈过程](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/7fa776a7-b884-401c-b954-6bb2a55243a6/concepts/29a326a7-32b9-46bb-93aa-10a09acef7c0)

## 截图
![- udacity](https://user-images.githubusercontent.com/16210915/47752983-5be8f900-dc96-11e8-9c7a-843c61cfb601.png)

## 具体描述
如图, 第一个视频下方文字有三处数学变量应该用Latex渲染.

**Comment by yifangwang08** [comment]
感谢反馈！
