### ISSUE TITLE
高级计算机计算与深度学习> RNN > [6.前馈过程] 翻译改进

### ISSUE THREAD

**Issue by ghost** [udacity/cn-cv-issue-report#91]
## 课程导航+地址
高级计算机计算与深度学习> RNN > [6.前馈过程](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/7fa776a7-b884-401c-b954-6bb2a55243a6/concepts/29a326a7-32b9-46bb-93aa-10a09acef7c0)

## 截图
![- udacity 1](https://user-images.githubusercontent.com/16210915/47753094-b71aeb80-dc96-11e8-8875-aed44ac8481f.png)

## 具体描述
Mean Square Error 似乎应翻译为 均方误差

**Comment by yifangwang08** [comment]
感谢反馈！
