### ISSUE TITLE
高级计算机计算与深度学习> RNN > [8.反向传播算法：理论] 翻译改进

### ISSUE THREAD

**Issue by ghost** [udacity/cn-cv-issue-report#92]
## 课程导航+地址
高级计算机计算与深度学习> RNN > [8.反向传播算法：理论](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/7fa776a7-b884-401c-b954-6bb2a55243a6/concepts/6fbfd066-6907-4f72-98b8-c5743818fa06)

## 截图
![- udacity 2](https://user-images.githubusercontent.com/16210915/47753514-19282080-dc98-11e8-8d24-0ff2b5958612.png)

## 具体描述
第二段, common derivatives 应该翻译为 常用导数, 或者 常见导数

**Comment by yifangwang08** [comment]
感谢反馈！
