### ISSUE TITLE
高级计算机计算与深度学习> RNN > [9.反向传播算法：示例(第一部分)] 方程式错误

### ISSUE THREAD

**Issue by ghost** [udacity/cn-cv-issue-report#93]
## 课程导航+地址
高级计算机计算与深度学习> RNN > [9.反向传播算法：示例(第一部分)](https://classroom.udacity.com/nanodegrees/nd891-cn/parts/c654cb90-9cbf-4971-9570-6cd03cfef8c7/modules/0b2b2185-02cb-4d06-9435-878b60d81cd1/lessons/7fa776a7-b884-401c-b954-6bb2a55243a6/concepts/00d69708-34de-45a2-a93d-4213f0cea51e)

## 截图
![- udacity 3](https://user-images.githubusercontent.com/16210915/47754264-9d7ba300-dc9a-11e8-89ff-d7b16a64e4a4.png)

## 具体描述
方程式11上方, 最后一个等号右边, 应该有一个负号.
话说分数符号不能显示. 估计是从Markdown转成网页时出了问题.

**Comment by yifangwang08** [comment]
感谢反馈！
